apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  type: ClusterIP #This means the service is only exposed within the cluster.
  selector:
    app: patient-service
  ports:
    - protocol: TCP
      port: 8080 # Expose the service internally on port 8080
      targetPort: 8080 # The target port your container