name: CI/CD Pipeline



on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Set Up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build JAR
      run: mvn clean package

    # Step 3: Build Docker Image
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/patient-service:${{ github.sha }} .

    # Step 4: Push Docker Image to Docker Hub
    - name: Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/patient-service:${{ github.sha }}

    # Step 5: Deploy to Kubernetes (Optional)
    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl apply -f ./kubernetes/patient-service-deployment.yaml
